### PR TITLE
fixed 1.8 -> 1.9 enderman metadata translation

### LINKED ISSUE #205: Enderman causes 1.8.9 client crash
Running Spigot 1.16.2 server and joining with a 1.8.9 client, the client crashes when it attempts to render an enderman. 

To reproduce, use the following plugin versions:
ViaBackwards-3.2.0-b166
ViaRewind-1.5.2-b61
ViaVersion-3.2.0-b465

Join the 1.16.2 server with a 1.8.9 client, switch to Creative mode, open the inventory and get a "Spawn Enderman" egg, then right-click on the ground with the egg to spawn an enderman. The client will crash.

Client error report:
```
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
Exit Code: -1
```

Full crash report: https://pastebin.com/wmT5AtLa
ViaVersion dump: https://dump.viaversion.com/7cdfa86a7c8c83e8d6dec702007e991f2b19425fdaecc073002cfcd7c11ddbc3
Spigot version git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2)

### PR DESCRIPTION
**Pull request by RaphiMC**
Fixed a issue that crashed 1.8 clients on 1.9 servers because of invalid metadata.
This should fix #205

### CODE REVIEW

File: core/src/main/java/de/gerrygames/viarewind/protocol/protocol1_8to1_9/metadata/MetadataRewriter.java [hunk 1]
```diff
@@ -47,12 +47,8 @@ public static void transform(Entity1_10Types.EntityType type, List<Metadata> lis
 							else entry.setValue(owner.toString());
 							break;
 						case BlockID:
-							int combined = (Integer) value;
-							int id = combined >> 4;
-							int data = combined & 0xF;
 							list.remove(entry);
-							list.add(new Metadata(metaIndex.getIndex(), MetaType1_8.Short, (short)id));
-							list.add(new Metadata(metaIndex.getIndex(), MetaType1_8.Byte, (byte)data));
+							list.add(new Metadata(metaIndex.getIndex(), MetaType1_8.Short, ((Integer) value).shortValue()));
```
Comment (tomcraft) [inline core/src/main/java/de/gerrygames/viarewind/protocol/protocol1_8to1_9/metadata/MetadataRewriter.java:51]: maybe this would be more prudent `((Number) value).shortValue()` ?

Comment (RaphiMC) [reply core/src/main/java/de/gerrygames/viarewind/protocol/protocol1_8to1_9/metadata/MetadataRewriter.java:51]: A BlockID is always a VAR_INT
